config/routes.rb
Auction2::Application.routes.draw do
  get "welcome/index"
  get "items/receipt"
  match "people/receipt/:id" => "people#receipt"
  match "people/resend_bidder_id/:id" => "people#resend_bidder_id"
  resources :items

  resources :people

  root :to => 'welcome#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :description, :donor_id, :minimum_bid, :name, :winning_bid, :winning_bidder_id
  validates_presence_of :name, :on => :create, :message => "can't be blank"
  validates_presence_of :minimum_bid, :on => :create, :message => "can't be blank"
  validates_presence_of :donor_id, :on => :create, :message => "can't be blank"
end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :phone_number
  
  validates_presence_of :first_name, :on => :create, :message => "can't be blank"
  validates_presence_of :last_name, :on => :create, :message => "can't be blank"
  validates_presence_of :email, :on => :create, :message => "can't be blank"
  validates_presence_of :phone_number, :on => :create, :message => "can't be blank"
  
  validates_uniqueness_of :email, :on => :create, :message => "must be unique"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  http_basic_authenticate_with :name => "qpauctionadmin", :password => '4ucti0n'
  
  
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def receipt
    @items = Item.find(:all, :order => 'winning_bidder_id')
  end
  

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  http_basic_authenticate_with :name => "qpauctionadmin", :password => '4ucti0n', :except => [:new, :create]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  def resend_bidder_id
    @person = Person.find(params[:id])
    UserMailer.returning_user_confirmation(@person).deliver
    respond_to do |format|
      format.html { redirect_to people_path, notice: "Bidder ID has been sent to #{@person.email}"}
      format.json {render :json => {success: true}}
    end
  end


  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  def receipt
    @person = Person.find(params[:id])
    @items = Item.where("winning_bidder_id = ?", params[:id])
  end


  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        UserMailer.signup_confirmation(@person).deliver
        format.html { redirect_to root_path, notice: "Registration Successful. An email was sent to #{@person.email} with your bidder number." }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= simple_form_for(@item) do |f| %>
  <%= f.input :name %>
  <%= f.input :description, :as => :text, :input_html => {:rows => 5} %>
  <%= f.input :donor_id, :collection => Person.all, :label_method => Proc.new {|t| "[#{t.id}]#{t.email}"}, :value_method => :id, :prompt => 'Select the Donor' %>
  <%= f.input :minimum_bid %>
  <%= f.input :winning_bidder_id, :collection => Person.all, :label_method => Proc.new {|t| "[#{t.id}]#{t.email}"}, :value_method => :id, :prompt => 'Select the Winner' %>
  <%= f.input :winning_bid %>
  <%= f.button :submit %>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div class="page_heading">
<h1>Listing items&nbsp;<%= link_to 'New Item', new_item_path, :class => "btn btn-primary" %></h1>
</div>
<table class="table table-stripped">
  <tr>
    <th>Item ID</th>
    <th>Name</th>
    <th>Donor</th>
    <th>Minimum bid</th>
    <th>Winning bidder</th>
    <th>Winning bid</th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.id %></td>
    <td><%= link_to item.name, item %></td>
    <td><%= Person.find(item.donor_id.to_i).email if item.donor_id %></td>
    <td><%= number_to_currency item.minimum_bid %></td>
    <td><%= Person.find(item.winning_bidder_id.to_i).email if item.winning_bidder_id %></td>
    <td><%= number_to_currency item.winning_bid %></td>
    <td>
      <%= link_to 'Show', item, {:class => "btn btn-mini btn-info"} %>
      <%= link_to 'Edit', edit_item_path(item), {:class => "btn btn-mini btn-success"} %>
      <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' %>
    </td>
  </tr>
<% end %>
</table>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/receipt.html.erb
<%- last_winner = nil %>
<%- total = 0 -%>
<%- grand_total = 0 -%>
<div class="pageHeader">
  <h1>Auction Receipts <small><%= number_to_currency Item.all.collect { |item| item.winning_bid rescue 0 }.reduce(:+) %></small></h1>
</div>

<table class="table table-stripped table-condensed">
  <thead>
    <tr>
      <th>Winning Bidder Name</th>
      <th>Auction Name</th>
      <th>Winning Bid</th>
    </tr>
  </thead>
  <tbody>
  <%- @items.each do |item| -%>
    <%- if item.winning_bidder_id -%>
      <%- current_winner = item.winning_bidder_id -%>
      <%- user = Person.find(current_winner) rescue nil %>
      <%- if last_winner && current_winner != last_winner -%>
      <tr>
        <td></td>
        <td><strong>Total:</strong></td>
        <td><strong><%= number_to_currency total %></strong></td>
      </tr>
      <%- total = item.winning_bid %>
      <%- else -%>
        <%- total += item.winning_bid %>
      <%- end -%>
      <tr>
        <td><%- unless last_winner == current_winner -%><strong><%= link_to "#{user.first_name} #{user.last_name}".titlecase, user %></strong>&nbsp;&mdash;&nbsp;<small><%= user.email %></small><%- end -%></td>
        <td><%= link_to item.name, item %></td>
        <td><%= number_to_currency item.winning_bid %></td>
      </tr>
      <%- last_winner = current_winner -%>
    <%- end -%>
  <%- end -%>
  <tr>
    <td></td>
    <td><strong>Total:</strong></td>
    <td><strong><%= number_to_currency total %></strong></td>
  </tr>
  </tbody>
</table>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>

<p>
  <b>Description:</b>
  <%= @item.description %>
</p>

<p>
  <b>Donor:</b>
  <%= @item.donor_id.present? ? Person.find(@item.donor_id.to_i).email : "No Donor Specified" %>
</p>

<p>
  <b>Winning bidder:</b>
  <%= Person.find(@item.winning_bidder_id.to_i).email if @item.winning_bidder_id %>
</p>

<p>
  <b>Minimum bid:</b>
  <%= number_to_currency @item.minimum_bid %>
</p>

<p>
  <b>Winning bid:</b>
  <%= number_to_currency @item.winning_bid %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Queen's Park Charity Auction</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Queen's Park Auction</a>
        <div class="nav-collapse">
          
        </div>
      </div>
    </div>
  </div>
<div class="container" style="margin-top:60px;">
  <%- if notice -%>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <%= notice %>
  </div>
  <%- end -%>
  
  <%- if alert -%>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <%= alert %>
  </div>
  <%- end -%>
  
  <%= yield %>
</div>
</body>
</html>

app/views/people/_form.html.erb
<%= simple_form_for(@person) do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :phone_number %>
  <%= f.button :submit %>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<div class="page_heading">
  <h1>Listing people <%= link_to 'New Person', new_person_path, {:class => "btn btn-primary"}%></h1>

</div>


<table class="table table-stripped">
  <tr>
    <th>Bidder ID</th>
    <th>Full Name</th>
    <th>Email</th>
    <th>Phone number</th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.id %></td>
    <td><%= link_to "#{person.first_name} #{person.last_name}", person %></td>
    <td><%= person.email %></td>
    <td><%= person.phone_number %></td>
    <td>
      <%= link_to "Resend ID", "people/resend_bidder_id/#{person.id}", :class => "btn btn-mini btn-warn" %>
      <%= link_to 'Show', person, {:class => "btn btn-mini btn-info"} %>
      <%= link_to 'Edit', edit_person_path(person), {:class => 'btn btn-mini btn-success'} %>
      <%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-mini btn-danger" %>
    </td>
  </tr>
<% end %>
</table>

<br />

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/receipt.html.erb
<%= @person.email %>
<%= number_to_currency @items.collect { |item| item.winning_bid rescue 0 }.reduce(:+) %>
<table>
  <%- @items.each do |item| -%>
  <tr>
    <td><%= item.name %></td>
    <td><%= number_to_currency item.winning_bid %></td>
  </tr>
  <%- end -%>
  <tr class="total">
    <td>Total:</td>
    <td><%= number_to_currency @items.collect { |item| item.winning_bid rescue 0 }.reduce(:+) %></td>
  </tr>
</table>

app/views/people/show.html.erb
<span class="span10 hero-unit">
  <h1><%= "#{@person.first_name} #{@person.last_name}" %>&nbsp;<small><%= @person.email %></small></h1>
  <br/>
  <h3>Your bidder id is <strong><%= @person.id %></strong>.</h3>
  <p>You will have to use this number to bid on items during the auction. Please write this number down.</p>
  <p>Thanks for registering!</p>
</span>

app/views/welcome/index.html.erb
<div class="span10 hero-unit">
  <h1>Queen's Park Auction</h1>
  <p>To participate as a bidder in the auction you must first register and get your bidder id.</p>
  <%= link_to "Register", new_person_path, :class => 'btn btn-primary btn-large' %>
</div>